---
version: '3.7'

services:
  popphp-app:
    build:
      context: ./docker/web
      dockerfile: Dockerfile.dev
    image: '${REPOSITORY_NAME}/${COMPOSE_PROJECT_NAME}-app:1.0.0-dev'
    container_name: '${COMPOSE_PROJECT_NAME}_app-dev'
    ports:
      - ${PORT}:80
    environment:
      - ENV=DEV
      - PORT=${PORT}

  popphp-mariadb:
    volumes:
      - ./docker/mariadb/seed/stage/:/docker-entrypoint-initdb.d/
