---
version: '3.7'

services:
  popphp-app:
    image: '${REPOSITORY_NAME}/${COMPOSE_PROJECT_NAME}-app:1.0.0-stage'
    container_name: '${COMPOSE_PROJECT_NAME}_app-stage'
    environment:
      - ENV=STAGE

  popphp-mariadb:
    volumes:
      - ./docker/mariadb/seed/stage/:/docker-entrypoint-initdb.d/
